ebean:
  dbScheme: spring_demo
  migration:

    run: true       # run database migrations on startup

datasource:
  url: jdbc:mysql://127.0.0.1:3306/spring_ebean?useUnicode=true&characterEncoding=utf8
  username: root
  password:
  driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
  client:
    service-url:
      defaultZone:
    register-with-eureka: true
    fetch-registry: true

spring:
  ai:
    qianfan:
      api-key:
      secret-key: